name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  GO_VERSION: "1.15"
  LINUX_ARCH: "amd64"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: GOARCH=${{ env.LINUX_ARCH }} ./build_linux.sh

  test-linux:
    name: Run tests on Linux amd64
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v2

      - name: Install test binaries
        env:
          GO111MODULE: off
        run: |
          go get github.com/containernetworking/cni/cnitool
          go get github.com/mattn/goveralls
          go get github.com/modocache/gover
      - name: test
        run: PATH=$PATH:$(go env GOPATH)/bin COVERALLS=1 ./test_linux.sh

      - name: Send coverage to coveralls
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PATH=$PATH:$(go env GOPATH)/bin
          gover
          goveralls -coverprofile=gover.coverprofile -service=github
